/// Month-end distributor stock by SKU with cover (last 3 months secondary) and health status.
table Stock
	lineageTag: 9116e0ab-65e9-4ccc-bdc6-b86f49957b39

	column 'Snapshot Date'
		dataType: dateTime
		isHidden
		lineageTag: 7165bba2-6c2a-49f0-8352-e709c4a5fb0b
		sourceColumn: Snapshot Date

	column 'Distributor ID'
		dataType: string
		isHidden
		lineageTag: b55ab6ae-4c5d-4851-bad2-fe206184022b
		sourceColumn: Distributor ID

	column 'SKU ID'
		dataType: string
		isHidden
		lineageTag: 0888a3dd-cc56-4942-a9a3-187def51817e
		sourceColumn: SKU ID

	column 'Closing Stock'
		dataType: int64
		lineageTag: 3b49bde5-b149-4645-8fd1-5a1d7b7cec16
		sourceColumn: Closing Stock

	column 'Stock Value'
		dataType: double
		lineageTag: c8a1b799-edd3-4391-8a6e-5da89289f3b4
		sourceColumn: Stock Value

	column 'Sales 3M Units'
		dataType: int64
		lineageTag: 5da21a7b-66b7-4afc-9e15-1b4d31df50d7
		sourceColumn: Sales 3M Units

	column 'Sales 3M Value PTD'
		dataType: double
		lineageTag: 0c091ff9-a1a9-4ca2-ab25-16cffe319d8a
		sourceColumn: Sales 3M Value PTD

	column 'Days of Stock'
		dataType: double
		formatString: 0
		lineageTag: 497258cf-21a6-49a6-ac03-85afbfa2deb1
		summarizeBy: none
		sourceColumn: Days of Stock

	column 'Stock Status'
		dataType: string
		lineageTag: 5f435bb8-7b98-4091-8d42-9dec043c6b87
		sourceColumn: Stock Status
		sortByColumn: 'Status Order'

	column 'Status Order'
		dataType: int64
		isHidden
		lineageTag: c4c86e16-8253-4f7a-a181-dcda7378d0d5
		summarizeBy: none
		sourceColumn: Status Order

	column 'Aged 90 Plus Value'
		dataType: double
		lineageTag: fb3b6425-76f4-42ca-9a78-c44d008d1330
		sourceColumn: Aged 90 Plus Value

	partition Stock = m
		mode: import
		source =
				let
				    Source = Csv.Document(Binary.Decompress(File.Contents(DataFolder & "fact_stock.csv.gz"), Compression.GZip), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Renamed = Table.TransformColumnNames(Headers, each Text.Replace(_, "_", " ")),
				    Blanks = Table.ReplaceValue(Renamed, "", null, Replacer.ReplaceValue, {"Days of Stock"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"Snapshot Date", type date}, {"Distributor ID", type text}, {"SKU ID", type text}, {"Closing Stock", Int64.Type}, {"Stock Value", type number}, {"Sales 3M Units", Int64.Type}, {"Sales 3M Value PTD", type number}, {"Days of Stock", type number}, {"Stock Status", type text}, {"Status Order", Int64.Type}, {"Aged 90 Plus Value", type number}}, "en-US")
				in
				    Typed

