export interface KpiDef {
  id: string
  name: string
  group: 'Sales' | 'Targets' | 'Distribution' | 'Product' | 'Inventory' | 'Collections' | 'Data Quality'
  definition: string
  formula: string
  interpretation: string
}

/** Single source of truth for KPI definitions (KPI page, card tooltips, docs/kpi_definitions.md). */
export const KPIS: KpiDef[] = [
  { id: 'sales', name: 'Sales (Net Sales)', group: 'Sales',
    definition: 'Invoice value after trade discount and before GST, on the selected sales basis (default: secondary sales net of returns).',
    formula: 'Σ (Quantity × Unit Price) − Σ Trade Discount   [returns carry negative quantity]',
    interpretation: 'The headline revenue number. Secondary (sell-out) shows real market demand; primary (sell-in) shows company billing.' },
  { id: 'primary', name: 'Primary Sales', group: 'Sales',
    definition: 'Company → distributor billing at distributor price (PTD).',
    formula: 'Σ Net Sales where Sales_Type = "Primary"',
    interpretation: 'Company revenue. Primary running ahead of secondary for several months means stock is being pushed into the pipeline (loading) and will show up as high distributor stock.' },
  { id: 'secondary', name: 'Secondary Sales', group: 'Sales',
    definition: 'Distributor → retailer billing at retailer price (PTR), net of sales returns.',
    formula: 'Σ Net Sales (Secondary) + Σ Net Sales (Sales Return, negative)',
    interpretation: 'True consumer-facing offtake through the distribution network. Targets and salesperson incentives are measured on secondary.' },
  { id: 'returns', name: 'Sales Return %', group: 'Sales',
    definition: 'Value of goods returned by outlets (damage, expiry, near-expiry) as a share of secondary sales.',
    formula: '|Σ Return Net Sales| ÷ Σ Secondary Net Sales × 100',
    interpretation: 'Healthy FMCG return rates are ~1–2%. Higher rates point to over-stocking at outlets, short-shelf-life SKUs or quality issues.' },
  { id: 'ps_ratio', name: 'Primary / Secondary Ratio', group: 'Sales',
    definition: 'Primary billing value (at distributor price) relative to net secondary value (at retailer price) for the same period.',
    formula: 'Primary Net Sales ÷ Net Secondary Sales',
    interpretation: 'Primary is billed ~8–10% below retailer price, so with pipeline growth a ratio of 0.88–1.02 is balanced. Persistently above ~1.02 = pipeline loading (stock building up at distributors); below ~0.88 = de-stocking or supply constraints.' },
  { id: 'target', name: 'Target', group: 'Targets',
    definition: 'Monthly secondary-sales target set at Salesperson × Category × Month (last-year actual × plan growth). Brand/SKU views disaggregate it with the SKU plan mix.',
    formula: 'Σ Target_Amount   (SKU level: Category Target × SKU plan share)',
    interpretation: 'The yardstick for achievement. Targets are not available below salesperson grain (beat / outlet type filters).' },
  { id: 'achievement', name: 'Achievement %', group: 'Targets',
    definition: 'Net secondary sales as a percentage of target for the same scope and period.',
    formula: 'Net Secondary Sales ÷ Target × 100',
    interpretation: '≥100% on / above plan, 90–100% watch, 80–90% under-performing, <80% is an exception that needs a recovery plan.' },
  { id: 'variance', name: 'Variance to Target', group: 'Targets',
    definition: 'Absolute gap between actual net secondary sales and target.',
    formula: 'Net Secondary Sales − Target',
    interpretation: 'Ranks where the money is: a 70% achiever with a small target can matter less than a 95% achiever with a big one.' },
  { id: 'growth', name: 'Growth % (vs LY)', group: 'Sales',
    definition: 'Change versus the same period last year (SPLY).',
    formula: '(Sales current period − Sales same period LY) ÷ Sales same period LY × 100',
    interpretation: 'Removes seasonality. Compare to category growth and price increase (~3–7% a year) to separate volume from price growth.' },
  { id: 'margin', name: 'Gross Margin', group: 'Product',
    definition: 'Net sales minus standard cost of goods sold.',
    formula: 'Net Sales − (Quantity × Standard Cost)',
    interpretation: 'Absolute profit pool. On secondary sales it represents the system margin (company + distributor).' },
  { id: 'margin_pct', name: 'Margin %', group: 'Product',
    definition: 'Gross margin as a share of net sales.',
    formula: 'Gross Margin ÷ Net Sales × 100',
    interpretation: 'Mix indicator. A fall with stable prices signals cost inflation (e.g. FY 2022-23) or a shift to lower-margin packs / higher discounts.' },
  { id: 'contribution', name: 'Contribution %', group: 'Product',
    definition: 'Share of an item in the total of its peer group for the same filters.',
    formula: 'Item Net Sales ÷ Total Net Sales × 100',
    interpretation: 'Portfolio concentration. Typically ~20% of SKUs drive ~80% of sales (Pareto).' },
  { id: 'active_distributors', name: 'Active Distributors', group: 'Distribution',
    definition: 'Distributors with at least one primary or secondary invoice in the period.',
    formula: 'COUNT DISTINCT Distributor_ID with sales in period',
    interpretation: 'Network health. A drop means distributors stopped billing (credit hold, termination, stock-out).' },
  { id: 'active_outlets', name: 'Active Outlets', group: 'Distribution',
    definition: 'Registered outlets on the beat plan that were open during the period (outlet universe under coverage).',
    formula: 'COUNT Outlet_ID where Opening_Date ≤ period end and not closed before period start',
    interpretation: 'Coverage — the number of outlets the sales team is expected to visit.' },
  { id: 'productive_outlets', name: 'Productive Outlets', group: 'Distribution',
    definition: 'Active outlets that placed at least one secondary order in a month (effective coverage), averaged over the months of the selected period.',
    formula: 'AVERAGE over months of COUNT DISTINCT Outlet_ID with a Secondary invoice',
    interpretation: 'Reach actually converted into billing each month. Measured monthly because almost every outlet orders at least once in a year.' },
  { id: 'productivity', name: 'Outlet Productivity %', group: 'Distribution',
    definition: 'Share of active outlets that billed in a month, averaged over the period.',
    formula: 'Avg monthly Productive Outlets ÷ Avg monthly Active Outlets × 100',
    interpretation: '≥65% good, 50–65% watch, <40% exception. Key salesperson-effectiveness KPI; combine with lines per call to see depth of the order.' },
  { id: 'sales_per_outlet', name: 'Sales per Outlet', group: 'Distribution',
    definition: 'Average net secondary sales per outlet that billed in the period.',
    formula: 'Net Secondary Sales ÷ Productive Outlets',
    interpretation: 'Throughput per outlet. Grow it by adding lines (range selling) and upgrading packs.' },
  { id: 'aov', name: 'Average Order Value (AOV)', group: 'Distribution',
    definition: 'Average value of a secondary invoice.',
    formula: 'Secondary Net Sales ÷ Number of Secondary Invoices (Orders)',
    interpretation: 'Order size. Low AOV with high order count = many small drops (costly to serve).' },
  { id: 'orders', name: 'Orders', group: 'Distribution',
    definition: 'Number of distinct secondary invoices (one per outlet visit that produced an order).',
    formula: 'COUNT DISTINCT Invoice_No (Secondary)',
    interpretation: 'Productive calls. Orders ÷ outlet visits = strike rate.' },
  { id: 'lpc', name: 'Lines per Call (LPC)', group: 'Distribution',
    definition: 'Average number of SKU lines per secondary order.',
    formula: 'Secondary invoice lines ÷ Orders',
    interpretation: 'Range-selling depth. Rising LPC means salespeople are selling more of the portfolio per visit.' },
  { id: 'stock_value', name: 'Stock Value', group: 'Inventory',
    definition: 'Distributor closing stock valued at distributor price (PTD) at the snapshot month-end.',
    formula: 'Σ Closing_Stock × Distributor Price',
    interpretation: 'Working capital sitting with distributors. Compare with sales (stock cover) rather than in isolation.' },
  { id: 'stock_cover', name: 'Stock Cover (Days of Stock)', group: 'Inventory',
    definition: 'How many days of sales the current closing stock can serve.',
    formula: 'Closing Stock ÷ (Last 3 months secondary quantity ÷ 91)',
    interpretation: 'Norm 7–45 days. <7 = risk of stock-out, 45–90 = overstock, >90 = slow-moving, no sales in 90 days = non-moving.' },
  { id: 'stockout_pct', name: 'Stock-out %', group: 'Inventory',
    definition: 'Share of distributor × SKU combinations with zero closing stock.',
    formula: 'Distributor-SKU combos with Closing = 0 ÷ Total active combos × 100',
    interpretation: 'Lost-sales risk. Stock-outs on high-velocity SKUs cost more than the % suggests — check value of sales at risk.' },
  { id: 'ageing', name: 'Stock Ageing', group: 'Inventory',
    definition: 'Closing stock split by age since receipt (FIFO): 0-30, 31-60, 61-90, 90+ days.',
    formula: 'Closing stock allocated to the latest receipts first (FIFO)',
    interpretation: 'Stock older than 90 days is at expiry / liquidation risk and needs a scheme or stock transfer.' },
  { id: 'collection_pct', name: 'Collection %', group: 'Collections',
    definition: 'Share of invoices raised in the period that has been collected by the report date.',
    formula: 'Collected against period invoices ÷ Invoice Amount × 100',
    interpretation: 'Cash conversion of the period’s billing.' },
  { id: 'collection_efficiency', name: 'Collection Efficiency (CEI)', group: 'Collections',
    definition: 'Collection Effectiveness Index — how much of what was collectible in the period was actually collected.',
    formula: '(Opening Outstanding + Invoiced − Closing Outstanding) ÷ (Opening Outstanding + Invoiced) × 100',
    interpretation: '>90% strong, 80–90% acceptable, <80% signals credit-control problems.' },
  { id: 'outstanding', name: 'Outstanding', group: 'Collections',
    definition: 'Unpaid balance of all primary invoices at the report date.',
    formula: 'Σ (Invoice Amount − Collections received up to report date)',
    interpretation: 'Receivables exposure. Compare with credit limit per distributor.' },
  { id: 'overdue', name: 'Overdue Amount', group: 'Collections',
    definition: 'Outstanding on invoices whose due date (invoice date + credit days) has passed.',
    formula: 'Σ Outstanding where Report Date > Due Date',
    interpretation: 'Bucketed 0-30 / 31-60 / 61-90 / 90+ days past due; 90+ is a bad-debt risk and a trigger for credit hold.' },
  { id: 'days_to_collect', name: 'Average Days to Collect', group: 'Collections',
    definition: 'Amount-weighted average number of days between invoice date and payment date.',
    formula: 'Σ (Payment Amount × (Payment Date − Invoice Date)) ÷ Σ Payment Amount',
    interpretation: 'Should sit at or below the credit period (15–30 days by distributor type).' },
  { id: 'dq_pct', name: 'Data Quality %', group: 'Data Quality',
    definition: 'Share of records passing all validation rules.',
    formula: '(Total Records − Exception Records) ÷ Total Records × 100',
    interpretation: 'Reported with every refresh so users can trust the numbers; exceptions are repaired or quarantined, never silently dropped.' },
]

export const kpi = (id: string) => KPIS.find(k => k.id === id)
